# Generated by Django 4.0.6 on 2022-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_post_snippets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippets',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read blog post...', max_length=255),
        ),
    ]
